Custom routes
quentingrchr/walk-of-art-back pull request #22
Opened 2022-06-30 11:56 UTC by Nephyrr

2022-06-30 18:41 UTC, VPKevin requested changes

2022-06-30 18:41 UTC, VPKevin commented on app/src/Entity/User.php
> +        "put" => [
Je sais pas quelle différence tu penses avoir entre put && `update_profile`
mais pour updaté un objet tu doit utiliser soit la méthode put soit patch en fonction du besoin et non post

2022-06-30 18:41 UTC, VPKevin commented on app/src/Entity/User.php
> +        'get' => [
Si ta methode c'est pour les artistes a la place de `'get' => [` mets `'artistes' => [`
&& mets là dans `collectionOperations`

2022-06-30 18:41 UTC, VPKevin commented on app/src/Entity/Exhibition.php
> +        'getOne' => [
Pas pertinent le get`'One'` ici on est dans itemOperations

2022-06-30 18:41 UTC, VPKevin commented on app/src/Common/ResponseRenderer.php
> +class ResponseRenderer
`Symfony\Component\HttpFoundation\JsonResponse` fais déjà le travail, t'as un exemple dans `SecurityController` quand tu auras rebase

2022-06-30 18:41 UTC, VPKevin commented on app/src/Controller/ExhibitionController.php
> +        return "Ce n'est pas la réservation de l'utilisateur connecté.";
Les retours doivent être fait en json avec code erreur, idem base toi sur ce que j'ai fais dans le `SecurityController`

2022-06-30 18:41 UTC, VPKevin commented on app/src/Controller/UserController.php
> +        return "Aucun utilisateur n'est connecté.";
Les 2 en json avec les propres code erreurs

2022-07-01 10:00 UTC, Nephyrr commented on app/src/Common/ResponseRenderer.php
> +class ResponseRenderer
Cette fonction est appelée au return de chaque custom routes

2022-07-17 13:09 UTC, closed without merging